# Workflow pour déployer du contenu statique sur GitHub Pages
name: Deploy static content to GitHub Pages

on:
  # Déclenchement lors d'un push sur la branche master (ou main)
  push:
    branches: ["master"]

  # Permet d'exécuter manuellement depuis l'onglet Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Assure-toi que tes fichiers HTML/CSS sont à la racine

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
